### ISSUE TITLE
Cannot find module '/node_modules/ISOToLanguage/lib/esm/index.js'

### ISSUE THREAD

**Issue by zvictor** [erikyo/ISOToLanguage#7]
Very nice project, thank you!  ❤️ 
I noticed 2 things, though:

1. "Weighing less than 10kb gzipped" seems incorrect. Everywhere it says 2mb.
2. I can't import it:

```haskell
Error: Cannot find module '/services/whatsapp-listener/node_modules/ISOToLanguage/lib/esm/index.js' imported from /services/whatsapp-listener/context.ts
    at finalizeResolution (/node_modules/.pnpm/ts-node@10.9.2_@types+node@20.11.24/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:366:11)
    at moduleResolve (/node_modules/.pnpm/ts-node@10.9.2_@types+node@20.11.24/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:801:10)
    at Object.defaultResolve (/node_modules/.pnpm/ts-node@10.9.2_@types+node@20.11.24/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:912:11)
    at /node_modules/.pnpm/ts-node@10.9.2_@types+node@20.11.24/node_modules/ts-node/src/esm.ts:218:35
    at entrypointFallback (/node_modules/.pnpm/ts-node@10.9.2_@types+node@20.11.24/node_modules/ts-node/src/esm.ts:168:34)
    at /node_modules/.pnpm/ts-node@10.9.2_@types+node@20.11.24/node_modules/ts-node/src/esm.ts:217:14
    at addShortCircuitFlag (/node_modules/.pnpm/ts-node@10.9.2_@types+node@20.11.24/node_modules/ts-node/src/esm.ts:409:21)
    at resolve (/node_modules/.pnpm/ts-node@10.9.2_@types+node@20.11.24/node_modules/ts-node/src/esm.ts:197:12)
    at nextResolve (node:internal/modules/esm/hooks:865:28)
    at Hooks.resolve (node:internal/modules/esm/hooks:303:30)
    ```

**Comment by erikyo** [comment]
You are correct, and that was indeed the original weight of the module when I initially published it (prior to incorporating some 'heavy' datasets). Upon further inspection, I can confirm that the compressed weight is just under 40KB (gzipped). This refers to the size of the package downloaded from the server, which serves it in that compressed format.

![image](https://github.com/wp-blocks/ISOToLanguage/assets/8550908/ce4b9b23-669d-4411-a0ee-350c3a5ebad6)

I look ahead as soon as you correct the json package I release a version where I also correct the readme, effectively it is really misleading

**Comment by zvictor** [comment]
All good. In my case it currently doesn't matter much as I am running it only in the server side, but I found it important to report it anyway.
